const IMAGE_DATA_DB_NAME = 'YTData';
const IMAGE_TITLE_DB_NAME = 'ImageTitles';
const THUMBNAIL_BUCKET_NAME = 'yt-thumbnailer';
const JWT_EXPIRATION_TIME = '1h';
const USER_PK_PREFIX = 'USER#';
const USER_SK_PREFIX = 'METADATA';
const IMAGE_SK_PREFIX = 'IMAGE#';
const LAST_ITEM_UPDATED_TIMESTAMP_PREFIX = 'LAST_ITEM_UPDATED_TIMESTAMP';

export default {
  IMAGE_DATA_DB_NAME,
  IMAGE_TITLE_DB_NAME,
  THUMBNAIL_BUCKET_NAME,
  JWT_EXPIRATION_TIME,
  USER_PK_PREFIX,
  USER_SK_PREFIX,
  IMAGE_SK_PREFIX,
  LAST_ITEM_UPDATED_TIMESTAMP_PREFIX,
};
